variables:
  DOCKER_CLI: docker:20.10.18-cli

stages:
  - deploy 

deploy_docker-compose:
  stage: deploy
  image: $DOCKER_CLI
  services:
    - docker:20.10.18-dind
  variables: 
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - chmod 400 $SSH_PRIVATE_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $USER@$HOST "cd ~/$DIR && chmod 777 gitlab-ci.sh && ./gitlab-ci.sh && git pull git@gitlab.com:dmakan/job.git master && docker-compose restart"
